"""add client_id to Session table

Revision ID: 34ddd094dec3
Revises: c18fc23fec93
Create Date: 2023-11-25 19:00:16.410240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ddd094dec3'
down_revision: Union[str, None] = 'c18fc23fec93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'session', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.drop_column('session', 'client_id')
    # ### end Alembic commands ###
