"""add role_type

Revision ID: 3d7cbcaa2b41
Revises: 62ac02775c5e
Create Date: 2023-11-27 19:54:49.619882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d7cbcaa2b41'
down_revision: Union[str, None] = '62ac02775c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('types', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'types')
    # ### end Alembic commands ###
