"""update unique fields

Revision ID: 919d0bbbe364
Revises: aa7878347aa5
Create Date: 2023-11-11 12:05:30.275959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919d0bbbe364'
down_revision: Union[str, None] = 'aa7878347aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'client', ['name'])
    op.create_unique_constraint(None, 'client', ['key'])
    op.create_unique_constraint(None, 'realm', ['name'])
    op.create_unique_constraint(None, 'role', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_constraint(None, 'realm', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    op.drop_constraint(None, 'client', type_='unique')
    # ### end Alembic commands ###
