"""add role_type as array(enum)

Revision ID: a3ab0a164dac
Revises: 3d7cbcaa2b41
Create Date: 2023-11-27 20:05:35.383771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3ab0a164dac'
down_revision: Union[str, None] = '3d7cbcaa2b41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'types',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'types',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
