version: "3.8"

services:
  database:
    image: postgres
    env_file:
      - ../.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-debug
    env_file:
      - ../.env
    volumes:
        - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      - database

  messaging_service:
        image: rabbitmq:3.7-management
        ports:
            - "5672:5672"
            - "15672:15672"
        healthcheck:
            test: [ "CMD", "rabbitmqctl", "status" ]
            interval: 5s
            timeout: 10s
            retries: 10
        restart: always