version: "3.8"

services:
  database:
    container_name: authsure-db
    image: postgres
    env_file:
      - ../.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  app:
    container_name: authsure-api
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - database
