version: "3.8"

services:
  database:
    container_name: authsure-db
    image: postgres
    env_file:
      - ../.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 120

  app:
    container_name: authsure-api
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-debug
    env_file:
      - ../.env
    volumes:
        - ..:/app
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy

  messaging_service:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always
